### ISSUE TITLE
Schema dont work with tab

### ISSUE THREAD

**Issue by Cirrusware** [koumoul-dev/vuetify-jsonschema-form#54] opened 2019-11-28 10:30 UTC
Hello,

I have an issue with tabulation,  Koumoul overwrite my global object when I change data in the last tab.
tab1 and tab2 share the same properties object (customFields).

![image](https://user-images.githubusercontent.com/5724417/69798656-fdac8380-11d1-11ea-9c9a-b1e87eaec84c.png)

customFields object is ok
![image](https://user-images.githubusercontent.com/5724417/69798708-1c127f00-11d2-11ea-95eb-f3cc0da86a20.png)

customFields object is overwritten by next data from the last tab
![image](https://user-images.githubusercontent.com/5724417/69798740-27fe4100-11d2-11ea-969d-d54e5980f64c.png)

Have you an idea ?

Thanks

{
  "$id": "https://example.com/person.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "x-options": {
    "allOfTabs": true
  },
  "allOf": [
    {
      "$ref": "#/definitions/tab0"
    },
    {
      "$ref": "#/definitions/tab1"
    },
    {
      "$ref": "#/definitions/tab2"
    }
  ],
  "definitions": {
    "tab0": {
      "title": "Général",
      "properties": {
        "customId": {
          "type": "string",
          "title": "Code Client",
          "x-class": "xs4",
          "readOnly": true
        },
        "name": {
          "type": "string",
          "title": "Nom",
          "x-class": "xs4"
        },
        "email": {
          "type": "string",
          "title": "E-mail",
          "x-class": "xs4",
          "format": "email"
        },
        "phone": {
          "type": "string",
          "title": "Téléphone",
          "x-class": "xs4",
          "format": "tel"
        },
        "fax": {
          "type": "string",
          "title": "Fax",
          "x-class": "xs4",
          "format": "tel"
        }
      }
    },
    "tab1": {
      "title": "Adresse",
      "properties": {
        "customFields": {
          "type": "object",
          "properties": {
            "Adresse1": {
              "type": "string",
              "title": "Adresse 1",
              "x-class": "xs4",
              "format": "text"
            },
            "Adresse2": {
              "type": "string",
              "title": "Adresse 2",
              "x-class": "xs4",
              "format": "text"
            },
            "CodePostal": {
              "type": "string",
              "title": "Code Postal",
              "x-class": "xs4",
              "format": "text"
            },
            "Ville": {
              "type": "string",
              "title": "Ville",
              "x-class": "xs4",
              "format": "text"
            },
            "Dpt": {
              "type": "string",
              "title": "Département",
              "x-class": "xs4",
              "format": "text"
            }
          }
        }
      }
    },
    "tab2": {
      "title": "Détails",
      "properties": {
        "customFields": {
          "type": "object",
          "properties": {
            "Cible": {
              "type": "array",
              "title": "Cible",
              "x-class": "xs4",
              "items": {
                "type": "string",
                "oneOf": [
                  {
                    "const": "ABA",
                    "title": "ABA"
                  },
                  {
                    "const": "ADE",
                    "title": "ADE"
                  },
                  {
                    "const": "BVI",
                    "title": "BVI"
                  },
                  {
                    "const": "CJE",
                    "title": "CJE"
                  },
                  {
                    "const": "EMA",
                    "title": "EMA"
                  }
                ]
              }
            },
            "TelSiege": {
              "type": "string",
              "title": "Téléphone Siège",
              "x-class": "xs4",
              "format": "tel"
            },
            "Effectif": {
              "type": "integer",
              "title": "Effectif",
              "x-class": "xs4",
              "format": "text"
            },
            "Ca": {
              "type": "integer",
              "title": "Chiffre d'Affaire",
              "x-class": "xs4",
              "format": "text"
            }
          }
        }
      }
    }
  }
}

**Comment by Cirrusware** [comment] 2019-12-06 14:56
Hello, Have you an idea ?
Have you need more explanations ?

Thanks

**Comment by albanm** [comment] 2019-12-06 20:53
Sorry, it is an edge case that I didn't think of. I just tried to make it work but couldn't find a proper solution right now and I lack the time to dive deeper.

**Comment by albanm** [comment] 2019-12-06 20:56
I thought it was related to the [cleanExtraProperties method](https://github.com/koumoul-dev/vuetify-jsonschema-form/blob/master/lib/components/Property.vue#L884). If so I could have added an option to disable removal of additional properties. But no it doesn't fix your case.

**Comment by Cirrusware** [comment] 2019-12-07 08:40
Ok Alban, no problem :-)
I will look at it (cleanExtraProperties).

Thanks for your advice. if I find something, I'll keep you informed.
This case is very important for mine and certainly other people.

**Comment by Cirrusware** [comment] 2019-12-07 15:46
I get nothing with cleanExtraProperties function.

A waiting solution: 
I get all the changed values and copy each value into a new object.

**Comment by sobrinho** [comment] 2020-03-30 14:39
If you want the tab to be in a nested property, you need to declare it explicitly:

```json
{
  "$id": "https://example.com/person.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Combinations",
  "description": "Rendering a root allOf as tabs",
  "type": "object",
  "x-options": {
    "allOfTabs": true
  },
  "allOf": [
    {
      "$ref": "#/definitions/realWorldEntity"
    },
    {
      "$ref": "#/definitions/socialMediaEntity"
    }
  ],
  "definitions": {
    "realWorldEntity": {
      "title": "Main infos",
      "properties": {
        "blah": {
          "type": "object",
          "properties": {
            "address": {
              "type": "string",
              "maxLength": 2000
            },
            "credit_card": {
              "type": "number"
            },
          }
        }
      },
    },
    "socialMediaEntity": {
      "title": "Social media",
      "properties": {
        "twitter": {
          "type": "string"
        },
        "facebook": {
          "type": "string"
        }
      }
    }
  }
}
```

That's because the library can't assume that you want a nested schema inside a tab instead of a flat one, it is "redundant" in the schema but by design.

@koumoul-dev you can close this one.

**Closed** 2020-04-15 20:58 UTC
