### ISSUE TITLE
Vuetify props don't get passed / rendered correctly

### ISSUE THREAD

**Issue by MagiciMan** [koumoul-dev/vuetify-jsonschema-form#292] opened 2021-08-17 22:27 UTC
Looking at the example of using Vuetify props through X-props, the chips prop don't seem to be working : 

```
const model = {
	chipsEnumProp: []
}

const options =  {}

const schema = {
	type: 'object',
	properties: {
		chipsEnumProp: {
			type: 'array',
			description: 'I\'m an array of strings from an enum with a bunch of additional props',
			'x-props': {
				chips: true,
				deletableChips: true,
				soloInverted: true,
				prependIcon: 'mdi-heart'
			},
			items: {
				type: 'string',
				enum: [
					'value 1',
					'value 2'
				]
			}
		}
	}
}

Vue.component('VJsf', VJsf.default)

new Vue({
  el: '#app',
  vuetify: new Vuetify(),
  data: {
    model,
    options,
    schema,
    valid: null
  },
  methods: {
    logEvent(key, $event) {
      console.log('vjsf event', key, $event)
    }
  }
})
```

![image](https://user-images.githubusercontent.com/77407563/129808870-8931fb50-3dbe-4356-8634-482c276827a0.png)

**Comment by albanm** [comment] 2021-08-18 06:32
Yes, that is right. Duplicate of https://github.com/koumoul-dev/vuetify-jsonschema-form/issues/281

**Closed** 2021-08-18 06:32 UTC
